---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgB/9p84WQWf4HrU8goxrMZEmUDpmJNFG5x+FheciwHDR1rbMmooG2eLAljykTw0oESzAW3FsMaKdyHijWsFC2lKc/kJG1/Nk/xn7wg/ki0yJesy9GMbf2j/0bRsnJm8V4XoaS1xjhU4/Hhllr2kjR35DJMebiWF4VMcGJWH/AJGFRLz3FhPktzx06Hk5mO75pJ2D3K1tnsE5v+qpcg0WG6ieSqzliGpr/ZUN6J1wZEQSa9VQ2Jc0GdhJykvdD/T8gSiAwp+e2Rtbn5tWTJYbPudNXmgZUarpcLqk0hq9YNmQ8ITjVL5w3inRB7QFyo0nijZjgeSkXTE9YPEQv9XzPVm79wCHHW29gbt4A4hyiBguM0YPKzVHzTLMaSpUixetgJIWLzoVuyU33Ecs+eyg8VQXjAQb7PceGNgBhKKof5VvMTKZWJ2imk68OLN51nUOsNcNnzflOA3dQlF9vPa8HF8IIwITcNLu3EDCK5SfiPWDOYOOmngVXbTW3pRzW8JUs9hvQAJX8jbF98lss2RgQP2dN/Mk9FFhOuPf3LKzT8YPYATcWfkaQExdtZLqneGB7GANNWbBMZoFjVTm0u2ZaRF2LJnVpqOdnBQf7NDdXEhptszGWppmcaq+PWwVH6+cw1xwFsOFdyvyYJ+c6VNGrdsX44Oh0LG19iloKpPIAd1mF9MrhB7aTWH8wSc6XmOb92llP7apwN3rSFYSavVpA==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
